Fix unit tests
* Fix Invalid Chai property: object
* Invalid Chai property: function
* Fix Error: Invalid Chai property: lase
* Fix Terms: Invalid Chai property: equal.true
* Fix PatientData should dispatch the message creation action
* Fix PatientInfo "before each" hook
* Fix should set `stats` to state
* Fix should show open a modal for removing a patient when their remove icon is clicked
* Fix should set a debounced call of the `onUpdateChartDateRange` prop method
* Fix should set a debounced call of the `onUpdateChartDateRange` prop method
* Fix __Rewire__  is not a function
* Fix should set a debounced call of the `onUpdateChartDateRange` prop method
* Fix "should console.error when required props not provided"
     This was a bug in this old prop-types version.
* Webpack: test is more like development
* Fix Can't resolve 'react-addons-test-utils'
    'react-addons-test-utils' has been deprecated, replaced by 'react-dom/test-utils' since react 15.5